require 'rake/clean'

SRC = 'thesis'
OUTPUT = "#{SRC}.pdf"

CLEAN.include(%w{*.aux *.bbl *.blg *.log *.toc})
CLOBBER.include(%w{*.pdf})

task :default => OUTPUT

file OUTPUT => [:clean, :once] do
  sh "bibtex --terse #{SRC}"
  # because the TOC and refs won't be complete:
  (1..2).each do
    Rake::Task['once'].execute
  end
end

desc "Compile the document once"
task :once do
  sh "xelatex #{SRC}"
end

desc "Compile and view #{OUTPUT}"
task :debug => [OUTPUT] do
  sh "open #{OUTPUT}"
end

